apiVersion: v1
kind: Secret
metadata:
  name: {{ template "k8s-db-postgres.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  postgres-user: {{ .Values.postgresql.postgresUser | b64enc | quote }}
