# Default values for elasticsearchs-singlenode.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
host: default.svc.cluster.local
path: /
annotations:
  #kubernetes.io/tls-acme: "true"
  kubernetes.io/ingress.class: "nginx"    
image:
  repository: lakowske/elasticsearch-cors
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: elasticsearch
  type: ClusterIP
  externalPort: 9200
  internalPort: 9200
  externalServiceName: elasticsearch
  externalName: 192.168.99.100
  externalIPs:
    - 192.168.99.100

resources:
  limits:
    cpu: 1000m
    memory: 2500Mi
  requests:
    cpu: 1000m
    memory: 2200Mi
