dependencies:
  - name: minikube-registry
    version: ">0.0.1"
    repository: https://lakowske.github.io/charts/
dependencies:
  - name: docker-registry-web
    version: ">0.0.1"
    repository: https://lakowske.github.io/charts/
