apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rook-operator
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        name: rook-operator
    spec:
      containers:
      - name: rook-operator
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        args: ["operator"]
        env:
        - name: ROOKD_REPO_PREFIX
          value: quay.io/rook
