# This chart defines sethlakowske.com dependencies
nginx-ingress:
  controller:
    service:
      type: ClusterIP
      # Override with --set
      # nginx-ingress.controller.service.externalIPs =
      # {192.168.99.101, 192.168.99.102, ...}
      externalIPs:
        - 192.168.99.100

blog:
  path: /
  annotations:  
    #kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
  tlsConf: null
#    tls:
#      - hosts:
#          - localkube
#        secretName: seth-tls
  host: sqkube    
        
