# This chart defines sethlakowske.com dependencies
nginx-ingress:
  controller:
    service:
      type: ClusterIP
      # Override with --set
      # nginx-ingress.controller.service.externalIPs =
      # {192.168.99.101, 192.168.99.102, ...}
      externalIPs:
        - 192.168.99.100

blog:
  path: /
  annotations:  
    #kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
  tlsConf: null
#    tls:
#      - hosts:
#          - localkube
#        secretName: seth-tls
  host: sqkube    

elasticsearch:
  ImagePullPolicy: "IfNotPresent"
  MasterReplicas: 1
  DataReplicas: 1
  ClientReplicas: 1
  DataStorageClass: "rook-block"
  DataStorageClassVersion: "beta"
  DataStorage: "20Gi"  
  DataMemoryRequests: "1Gi"
  DataMemoryLimits: "1500Mi"
  DataHeapSize: "500m"
  MasterHeapSize: "200m"
  MasterMemoryLimits: "512Mi"
  MasterMemoryRequests: "256Mi"
  ClientMemoryLimits: "300Mi"
  ClientMemoryRequests: "160Mi"
  ClientHeapSize: "200m"
