# This chart defines sethlakowske.com dependencies
nginx-ingress:
  controller:
    service:
      type: ClusterIP
      # Override with --set
      # nginx-ingress.controller.service.externalIPs =
      # {192.168.99.101, 192.168.99.102, ...}
      externalIPs:
        - 192.168.99.100

blog:
  path: /
  annotations:  
    #kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
  tlsConf: null
#    tls:
#      - hosts:
#          - localkube
#        secretName: seth-tls
  host: sqkube    

elasticsearch:
  MasterReplicas: 1
  DataReplicas: 1
  ClientReplicas: 1
  DataStorageClass: "rook-block"
  DataStorageClassVersion: "beta"
  DataMemoryRequests: "1Gi"
  DataHeapSize: "768m"
  DataStorage: "10Gi"
  MasterMemoryLimits: "256Mi"
  MasterMemoryRequests: "128Mi"
  ClientMemoryLimits: "256Mi"
  ClientMemoryRequests: "128Mi"
