apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
{{ toYaml .Values.annotations | indent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              {{ if .Values.applyServiceNameDirect }}
              serviceName: {{ .Values.service.name }}
              {{ else }}
              serviceName: {{ .Release.Name}}-{{ .Values.service.name }}              
              {{ end }}
              servicePort: {{ .Values.service.externalPort }}

