{{ if .Values.persistence.create }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.persistence.hostpath }}"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pvc
spec:
  storageClassName: manual
  selector:
    matchLabels:
      type: local
  resources:
    requests:
      storage: 9Gi      
  accessModes:
    - ReadWriteOnce    
{{ end }}
