apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}  
spec:
  rules:
    - host: {{ .Values.service.externalServiceName }}.{{ .Values.host }}
      http:
        paths: 
          - path: {{ .Values.path }}
            backend:
              serviceName: {{ template "fullname" . }}
              servicePort: {{ .Values.service.externalPort }}
{{ if .Values.tlsConf }} 
{{ toYaml .Values.tlsConf | indent 2 }}
{{ end }}
  
