apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: {{ .Values.pvc.claimName }}
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  volumeName: {{ .Values.pvc.volumeName }}
